package edu.sc.seis.sod.bag;

import java.time.Instant;

import org.apache.log4j.BasicConfigurator;

import edu.sc.seis.seisFile.TimeUtils;
import edu.sc.seis.sod.mock.seismogram.MockSeismogram;
import edu.sc.seis.sod.model.common.FissuresException;
import edu.sc.seis.sod.model.common.SamplingImpl;
import edu.sc.seis.sod.model.seismogram.LocalSeismogramImpl;
import junit.framework.TestCase;

// JUnitDoclet end import
/**
 * Generated by JUnitDoclet, a tool provided by ObjectFab GmbH under LGPL.
 * Please see www.junitdoclet.org, www.gnu.org and www.objectfab.de for
 * informations about the tool, the licence and the authors.
 */
public class CutTest extends TestCase {

    LocalSeismogramImpl seis;

    Instant time = TimeUtils.parseISOString("2000-12-31T23:59:59.000Z");

    int[] data;
    static {
        BasicConfigurator.configure();
    }

    public CutTest(String name) {
        super(name);
    }

    protected void setUp() throws Exception {
        super.setUp();
        data = new int[101];
        for(int i = 0; i < data.length; i++) {
            data[i] = 0;
            // create test data creates 20sps data
            if(i % 20 == 0) {
                data[i] = 1;
            } // end of if ()
        } // end of for ()
        seis = MockSeismogram.createTestData("est", data, time);
    }

    protected void tearDown() throws Exception {
        seis = null;
        data = null;
        super.tearDown();
    }

    public void testShiftBegin() throws Exception {
        Instant begin = time;
        Instant end = seis.getEndTime();
        SamplingImpl samp = (SamplingImpl)seis.sampling_info;
        begin = begin.plus(samp.getPeriod());
        Cut cut = new Cut(begin, end);
        LocalSeismogramImpl out = cut.apply(seis);
        assertTrue("Num points is one less " + out.num_points + " "
                + seis.num_points, out.num_points == seis.num_points - 1);
    }

    public void testShiftEnd() throws Exception {
        Instant begin = time;
        Instant end = seis.getEndTime();
        SamplingImpl samp = (SamplingImpl)seis.sampling_info;
        end = end.minus(samp.getPeriod());
        Cut cut = new Cut(begin, end);
        LocalSeismogramImpl out = cut.apply(seis);
        assertEquals("Num points is one less " + out.num_points + " "
                + seis.num_points, out.num_points , seis.num_points - 1);
    }

    public void testOffBegin() throws Exception {
        Instant begin = time;
        Instant end = seis.getEndTime();
        SamplingImpl samp = (SamplingImpl)seis.sampling_info;
        begin = begin.minus(samp.getPeriod());
        Cut cut = new Cut(begin, end);
        LocalSeismogramImpl out = cut.apply(seis);
        assertEquals("Num points is equal " + out.num_points + " "
                + seis.num_points, out.num_points , seis.num_points );
    }

    public void testOffEnd() throws Exception {
        Instant begin = time;
        Instant end = seis.getEndTime();
        SamplingImpl samp = (SamplingImpl)seis.sampling_info;
        end = end.plus(samp.getPeriod());
        Cut cut = new Cut(begin, end);
        LocalSeismogramImpl out = cut.apply(seis);
        assertEquals("Num points is equal  " + out.num_points + " "
                + seis.num_points, out.num_points , seis.num_points );
    }
    
    public void testExactSeisTimes() throws FissuresException {
        Instant begin = time;
        Instant end = seis.getEndTime();
        Cut cut = new Cut(begin, end);
        LocalSeismogramImpl out = cut.apply(seis);
        assertEquals("Num points is same less " + out.num_points + " "
                + seis.num_points, out.num_points , seis.num_points );
    }
}
