package edu.sc.seis.sod.bag;

import static org.junit.Assert.*;

import org.junit.Test;

/**
* Generated by JUnitDoclet, a tool provided by
* ObjectFab GmbH under LGPL.
* Please see www.junitdoclet.org, www.gnu.org
* and www.objectfab.de for informations about
* the tool, the licence and the authors.
*/


public class DistAzTest
{
  
    @Test
    public void sueTest() {
        DistAz dz = new DistAz(29.331, -113.697, 29.331, -113.697);
        assertEquals(0, dz.getDelta(), 0.000001);
    }
  
}
